# Generated by Django 4.2.4 on 2023-08-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=20)),
                ('empDateofJoin', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attandancetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Attendance', models.BooleanField()),
                ('WorkingHour', models.TimeField()),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assestapp.employee')),
            ],
        ),
    ]
