# Generated by Django 4.2.4 on 2023-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0002_alter_attandancetable_workinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandancetable',
            name='WorkingHour',
            field=models.CharField(max_length=6),
        ),
    ]
