# Generated by Django 4.2.4 on 2023-08-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assestapp', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
